add check for qemu-static
qemu-static.conf is a file that is also needed for the installer to work. So add a check and exit installer if it's not found.

Also update version number to 1.2.9, forgot that in the previous commit.

diff --git a/manjaro-arm-installer b/manjaro-arm-installer
--- a/manjaro-arm-installer
+++ b/manjaro-arm-installer
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # *****************************
-#       Version 1.2.8
+#       Version 1.2.9
 # *****************************
 
 # Set globals
@@ -50,6 +50,10 @@ for i in "${DEPENDNECIES[@]}"; do
   fi
 done
 
+if [ ! -f "/usr/lib/binfmt.d/qemu-static.conf" ]; then
+    echo "qemu-static.conf file is missing. Please install the relevant package."
+    exit 1
+fi
 
 
 # Functions
